languages:
  - id: java
    name: Java
    extension: java
    repo: git@github.com:metaborg/java-front.git
    path: lang.java
    sources:
      - id: apache-commons-lang
        repo: https://github.com/apache/commons-lang.git
  - id: ocaml
    name: OCaml
    extension: ml
    repo: git@github.com:metaborgcube/metaborg-ocaml
    path: org.metaborg.lang.ocaml
    sources:
      - id: facebook-flow
        repo: https://github.com/facebook/flow.git